// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOv3y2WrnzzeOhD26NWm4BzHs18GEmRQA',
    appId: '1:29857906401:web:2556369d97956009da81a0',
    messagingSenderId: '29857906401',
    projectId: 'miapp-a4325',
    authDomain: 'miapp-a4325.firebaseapp.com',
    storageBucket: 'miapp-a4325.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGBqbMqumEBL_5l-gWi5QgxXCOvfF7hEc',
    appId: '1:29857906401:android:b63510449e72db7bda81a0',
    messagingSenderId: '29857906401',
    projectId: 'miapp-a4325',
    storageBucket: 'miapp-a4325.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOv3y2WrnzzeOhD26NWm4BzHs18GEmRQA',
    appId: '1:29857906401:web:ab3126d2e671f79cda81a0',
    messagingSenderId: '29857906401',
    projectId: 'miapp-a4325',
    authDomain: 'miapp-a4325.firebaseapp.com',
    storageBucket: 'miapp-a4325.firebasestorage.app',
  );

}